### PR TITLE
adding attention message

### PR DESCRIPTION
**Pull request by choldgraf**
@yuvipanda

### CODE REVIEW

**Review by rgbkrk — APPROVED** [review]

**Comment by freeman-lab** [comment]
missing a closing tag?

**Comment by choldgraf** [comment]
oops, updated!

**Comment by choldgraf** [comment]
tbh I think we're pretty close to telling people they can try out beta.mybinder.org if they're willing to live on the cutting edge. We're pretty close to finalizing the URL API and then have a few things to finish up but it'll be a matter of days / 1-2 weeks at most I think (famous last words)

**Comment by rgbkrk** [comment]
The beta frontpage is looking really slick!

**Pull request closed without merging**
